fix validation methods return type
Fix workflow
remove unused files
Update rollup config

diff --git a/.github/workflows/pull-request-opened.yml b/.github/workflows/pull-request-opened.yml
--- a/.github/workflows/pull-request-opened.yml
+++ b/.github/workflows/pull-request-opened.yml
@@ -1,4 +1,4 @@
-name: build and test ikomida dev lib before pull request merge
+name: build and test ikomida shared logics lib before pull request merge
 on:
   pull_request:
     branches:
@@ -34,12 +34,12 @@ jobs:
           LIB_NAME=$(node --eval="process.stdout.write(require('./package.json').name)")
           LIB_VERSION=$(node --eval="process.stdout.write(require('./package.json').version)")
           LIB_VERSION_REMOTE=$(npm view "${LIB_NAME}" version)
-          if [[ $LIB_VERSION > $LIB_VERSION_REMOTE ]]; then
-            echo "Lib package version is correct"
-            exit 0
-          else 
-            echo "Error: you mast update lib package version"
-            exit 1
+          if { echo "$LIB_VERSION"; echo "$LIB_VERSION_REMOTE"; } | sort --version-sort --check; then
+              echo "Error: you mast update lib package version"
+              exit 1
+          else
+              echo "Lib package version is correct"
+              exit 0
           fi
       - name: Install dependencies
         run: yarn install --frozen-lockfile
